const ADMIN_EMAIL="palivo@admin.palivotattoo.com.br";
const categoryNames={"fine-art":"Fine Art","fine-line":"Fine Line","cristao":"Cristão","realismo":"Realismo","escrita":"Escrita"};
const categoryPrefixes={"fine-art":"FA","fine-line":"FL","cristao":"CR","realismo":"RE","escrita":"ES"};
let client,currentRows=[];
const $=selector=>document.querySelector(selector);
function escapeHTML(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
function money(value){return Number(value||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function publicImage(path){return path?`${window.PALIVO_SUPABASE.url}/storage/v1/object/public/tattoos/${path}`:""}
function message(target,text,type=""){target.textContent=text;target.className=`message show ${type}`;if(target===$("#appMessage"))setTimeout(()=>target.classList.remove("show"),4500)}
function clearMessage(target){target.className="message";target.textContent=""}
function setBusy(button,busy,label){if(busy){button.dataset.label=button.textContent;button.textContent=label;button.disabled=true}else{button.textContent=button.dataset.label||button.textContent;button.disabled=false}}

function configure(){const cfg=window.PALIVO_SUPABASE;if(!cfg||cfg.url.startsWith("COLE_")||cfg.publishableKey.startsWith("COLE_")||!window.supabase)throw new Error("Configuração do Supabase ainda não foi preenchida.");client=window.supabase.createClient(cfg.url,cfg.publishableKey)}
async function confirmAdmin(){const{data,error}=await client.rpc("is_admin");if(error||!data)throw new Error("Este usuário não possui permissão administrativa.")}
async function showDashboard(){await confirmAdmin();$("#loginView").hidden=true;$("#dashboardView").hidden=false;await loadRows()}
async function handleLogin(event){event.preventDefault();const button=event.submitter;clearMessage($("#loginMessage"));setBusy(button,true,"Entrando...");try{const username=$("#username").value.trim().toLowerCase();if(username!=="palivo")throw new Error("Usuário inválido.");const{error}=await client.auth.signInWithPassword({email:ADMIN_EMAIL,password:$("#password").value});if(error)throw new Error("Usuário ou senha incorretos.");await showDashboard()}catch(error){message($("#loginMessage"),error.message,"error");await client.auth.signOut()}finally{setBusy(button,false)}}
async function logout(){await client.auth.signOut();location.reload()}

function rowHTML(row){const available=row.status==="disponivel",label=available?"Disponível":row.status==="em_negociacao"?"Em negociação":"Indisponível";return `<article class="admin-row" data-id="${row.id}"><img src="${escapeHTML(publicImage(row.imagem_path))}" alt=""><div class="art-main"><strong>${escapeHTML(row.codigo)}</strong><span>${escapeHTML(row.categoria_nome)}</span></div><div class="prices"><span>De: ${money(row.preco_de)}</span><b>Por: ${money(row.preco_por)}</b></div><div class="status-control"><label class="switch" title="Disponível"><input class="availability" type="checkbox" ${available?"checked":""}><span></span></label><small>${label}</small></div><div class="row-actions"><button class="ghost edit">Editar</button><button class="delete">Excluir</button></div></article>`}
async function loadRows(){const list=$("#tattooList");list.innerHTML='<div class="loading">Carregando artes...</div>';const{data,error}=await client.from("tattoos").select("*").order("ordem",{ascending:true}).order("criado_em",{ascending:false});if(error){message($("#appMessage"),error.message,"error");return}currentRows=data||[];$("#artCount").textContent=`${currentRows.length} ${currentRows.length===1?"arte":"artes"}`;list.innerHTML=currentRows.length?currentRows.map(rowHTML).join(""):'<div class="empty">Nenhuma tatuagem cadastrada. Clique em “Nova tatuagem” para começar.</div>';bindRows()}
function bindRows(){$("#tattooList").querySelectorAll(".admin-row").forEach(el=>{const id=el.dataset.id;el.querySelector(".edit").onclick=()=>openEditor(currentRows.find(r=>r.id===id));el.querySelector(".delete").onclick=()=>deleteRow(id);el.querySelector(".availability").onchange=e=>toggleAvailability(id,e.target.checked,e.target)})}
async function toggleAvailability(id,checked,input){input.disabled=true;const status=checked?"disponivel":"indisponivel";const{error}=await client.from("tattoos").update({status}).eq("id",id);if(error){input.checked=!checked;message($("#appMessage"),`Não foi possível alterar: ${error.message}`,"error")}else message($("#appMessage"),checked?"Arte marcada como disponível.":"Arte marcada como indisponível.","success");input.disabled=false;await loadRows()}

function openEditor(row=null){const form=$("#tattooForm");form.reset();$("#recordId").value=row?.id||"";$("#currentImagePath").value=row?.imagem_path||"";$("#editorTitle").textContent=row?`Editar ${row.codigo}`:"Nova tatuagem";$("#categoria").value=row?.categoria||"fine-art";$("#categoria").disabled=Boolean(row);$("#status").value=row?.status||"disponivel";$("#precoDe").value=row?.preco_de??"";$("#precoPor").value=row?.preco_por??"";$("#autoCode").textContent=row?.codigo||`${categoryPrefixes[$("#categoria").value]} · próximo número automático`;const preview=$("#imagePreview");preview.hidden=!row?.imagem_path;preview.innerHTML=row?.imagem_path?`<img src="${escapeHTML(publicImage(row.imagem_path))}" alt="Imagem atual">`:"";$("#imagem").required=!row;$("#editorPanel").hidden=false;$("#editorPanel").scrollIntoView({behavior:"smooth",block:"start"})}
function closeEditor(){$("#editorPanel").hidden=true;$("#categoria").disabled=false;$("#tattooForm").reset()}
async function nextCode(categoria){const prefix=categoryPrefixes[categoria];const{data,error}=await client.from("tattoos").select("codigo").eq("categoria",categoria);if(error)throw error;const highest=(data||[]).reduce((max,row)=>{const match=String(row.codigo||"").match(new RegExp(`^${prefix}\\s*-\\s*(\\d+)$`,"i"));return match?Math.max(max,Number(match[1])):max},0);return{codigo:`${prefix}-${String(highest+1).padStart(3,"0")}`,ordem:highest+1}}
function safeFileName(file){const ext=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"");return`${Date.now()}-${crypto.randomUUID()}.${ext}`}
async function uploadImage(file){if(file.size>8*1024*1024)throw new Error("A imagem deve ter no máximo 8 MB.");const path=safeFileName(file);const{error}=await client.storage.from("tattoos").upload(path,file,{cacheControl:"3600",upsert:false});if(error)throw error;return path}
async function saveTattoo(event){event.preventDefault();const button=$("#saveBtn"),id=$("#recordId").value,oldPath=$("#currentImagePath").value,file=$("#imagem").files[0];setBusy(button,true,"Salvando...");let newPath="";try{if(file)newPath=await uploadImage(file);const existing=id?currentRows.find(row=>row.id===id):null;const categoria=existing?.categoria||$("#categoria").value;const generated=existing?{codigo:existing.codigo,ordem:existing.ordem}:await nextCode(categoria);const payload={codigo:generated.codigo,nome:generated.codigo,categoria,categoria_nome:categoryNames[categoria],preco_de:Number($("#precoDe").value),preco_por:Number($("#precoPor").value),status:$("#status").value,observacao:null,ordem:generated.ordem,imagem_path:newPath||oldPath};const query=id?client.from("tattoos").update(payload).eq("id",id):client.from("tattoos").insert(payload);const{error}=await query;if(error)throw error;if(newPath&&oldPath)await client.storage.from("tattoos").remove([oldPath]);closeEditor();message($("#appMessage"),id?"Tatuagem atualizada.":`Tatuagem ${generated.codigo} cadastrada.`,"success");await loadRows()}catch(error){if(newPath)await client.storage.from("tattoos").remove([newPath]);message($("#appMessage"),`Não foi possível salvar: ${error.message}`,"error")}finally{setBusy(button,false)}}
async function deleteRow(id){const row=currentRows.find(r=>r.id===id);if(!row||!confirm(`Excluir definitivamente a arte ${row.codigo}?`))return;const{error}=await client.from("tattoos").delete().eq("id",id);if(error){message($("#appMessage"),`Não foi possível excluir: ${error.message}`,"error");return}if(row.imagem_path)await client.storage.from("tattoos").remove([row.imagem_path]);message($("#appMessage"),"Tatuagem excluída.","success");await loadRows()}

document.addEventListener("DOMContentLoaded",async()=>{try{configure();$("#loginForm").addEventListener("submit",handleLogin);$("#logoutBtn").onclick=logout;$("#newBtn").onclick=()=>openEditor();$("#closeEditor").onclick=closeEditor;$("#cancelBtn").onclick=closeEditor;$("#tattooForm").addEventListener("submit",saveTattoo);$("#categoria").addEventListener("change",event=>{$("#autoCode").textContent=`${categoryPrefixes[event.target.value]} · próximo número automático`});$("#imagem").addEventListener("change",event=>{const file=event.target.files[0],preview=$("#imagePreview");if(file){preview.hidden=false;preview.innerHTML=`<img src="${URL.createObjectURL(file)}" alt="Prévia">`}});const{data}=await client.auth.getSession();if(data.session)await showDashboard()}catch(error){message($("#loginMessage"),error.message,"error")}});
